### ISSUE TITLE
what specific version of python 3? AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'

### ISSUE THREAD

**Issue by kuhanw** [suriyadeepan/tf_seq2seq_wrapper#45]
Hi all,

I am noticing an error which I am pretty sure has to do with version compatibility in tensorflow, when I try to execute 

model = seq2seq_wrapper.Seq2Seq(xseq_len=xseq_len,
                               yseq_len=yseq_len,
                               xvocab_size=xvocab_size,
                               yvocab_size=yvocab_size,
                               ckpt_path='ckpt/twitter/',
                               emb_dim=emb_dim,
                               num_layers=3
                               )

I get the message, AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'.

But I have installed tensorflow 0.12.0, my python version is 3.5.2. Is there a specific py3 version I need as well?

Thank You,

Kuhan

**Comment by LeenaShekhar** [comment]
This is due to TF incompatibility. Could you give a quick trial with 1.1.0?

**Comment by PedroPei** [comment]
There's no core_rnn_cell since Tensorflow 1.0.0.Simply erasing 'core_rnn_cell' like changing "tf.contrib.rnn.core_rnn_cell.DropoutWrapper" to "tf.contrib.rnn.DropoutWrapper" would help.

**Comment by kuhanw** [comment]
Thanks, I got it!
